server:
  port: 8003
  servlet:
    context-path: /batch

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: batch
    url: jdbc:mysql://localhost:3306/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_batch

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com:
      hubindeveloper:
        train:
          member:
            mapper: trace