server:
  port: 8002
  servlet:
    context-path: /business

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: business
    url: jdbc:mysql://localhost:3306/business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com:
      hubindeveloper:
        train:
          member:
            mapper: trace