server:
  port: 8002
  servlet:
    context-path: /business

spring:
  application:
    name: business
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: business
    url: jdbc:mysql://localhost:3306/business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com:
      hubindeveloper:
        train:
          business:
            mapper: trace

